---
title: "Lehrstuhl für Ökonometrie"
---

Aufgrund der aktuellen technischen Probleme bei den Informationsdiensten der Universität stellt der Lehrstuhl für Ökonometrie vorübergehend eine eigene Homepage bereit.

## Team

### Professor

-   [Christoph Hanck](mailto:christoph.hanck@uni-dortmund.de)

### Sekretariat

-   [Ilona Braun](mailto:Ilona.Braun.Uni@gmail.com)

### Akademischer Rat 

-   [Dr. Yannick Hoga](hogayannick@gmail.com) 

### Wissenschaftliche Mitarbeitende

-   [Martin Arnold](mailto:martchriarno@googlemail.com)
-   [Karolina Gliszczynska](gliszczynska.oek@gmail.com)
-   [Jens Klenke](mailto:jens.klenke.ude@gmail.com)
-   [Dr. Till Massing](mailto:tillmassing+oeko@gmail.com)
-   [Janine Langerbein](mailto:j.langerbein.oek@gmail.com)
-   [Thilo Reinschlüssel](mailto:rdie_winter2022@protonmail.com)

## Lehre

Materialien für unsere Kurse finden Sie auf den entsprechenden Kursseiten.  

#### Bachelorveranstaltungen 

-   [Deskriptive Statistik](https://jens-klenke.github.io/Desk_Stat_WiSe_22/)
-   [Einführung in die Ökonometrie](https://mca91.github.io/Eidoe22/)

##### Masterveranstaltungen 

-   [Methoden der Ökonometrie](https://github.com/karo93/Methoden2223)
-   [Recent Developments in Econometrics](https://jens-klenke.github.io/RDIE_WiSe_22/)

## Links 

-   [Universität Duisburg-Essen](https://www.uni-due.org/){target="_blank"}
-   [Fakultät für Wirtschaftswissenschaften](https://wiwi-uni-due.de){target="_blank"}
